import { mkdirSync, writeFileSync, copyFileSync } from 'node:fs';
const out = 'dist';
mkdirSync(`${out}/assets`, { recursive: true });
for (const name of ['styles.css', 'app.js']) copyFileSync(name, `${out}/${name}`);
const pages = [['index','Home'],['about','About Us'],['classes','Classes'],['events','Events'],['instructors','Instructors'],['gallery','Gallery'],['blogs','Blogs'],['contacts','Contacts']];
const link = (page) => `${page}.html`;
const button = (text, page, secondary = false) => `<a class="button ${secondary ? 'secondary' : ''}" href="${link(page)}">${text}</a>`;
const eyebrow = (text) => `<p class="eyebrow"><span></span>${text}</p>`;
const heading = (label,title,description) => `<section class="page-heading container">${eyebrow(label)}<h1>${title}</h1><p class="intro">${description}</p></section>`;
const image = (asset, alt, cls = '') => `<img class="${cls}" src="assets/${asset}.jpg" alt="${alt}" loading="lazy" width="1200" height="900">`;
const classData = [
  {id:'hatha',name:'Hatha Yoga',category:'Foundations',level:'Beginner friendly',text:'A slower practice with time to explore each posture, steady your breath, and find your own rhythm.',duration:'60 minutes',number:'01',tags:'beginner mindful'},
  {id:'vinyasa',name:'Vinyasa Flow',category:'Movement',level:'All levels',text:'Move through a flowing sequence of postures, connecting each movement with an easy, steady breath.',duration:'60 minutes',number:'02',tags:'flow'},
  {id:'restorative',name:'Restorative Yoga',category:'Stillness',level:'All levels',text:'Settle into supported shapes with blankets and props, creating space to slow down and rest.',duration:'45 minutes',number:'03',tags:'beginner mindful'},
  {id:'pranayama',name:'Breath & Meditation',category:'Awareness',level:'Beginner friendly',text:'Explore gentle breathing practices and guided moments of stillness. A little space for yourself.',duration:'30 minutes',number:'04',tags:'beginner mindful'}
];
function classCard(c) { return `<article class="class-card" data-class-tags="${c.tags}"><div class="card-top"><span class="eyebrow">${c.category}</span><span class="card-number">${c.number}</span></div><h3>${c.name}</h3><p>${c.text}</p><div class="card-meta"><span>${c.duration}</span><span>${c.level}</span></div><a class="text-link" href="contacts.html?class=${encodeURIComponent(c.name)}">Enquire about this class</a></article>`; }
const invitation = `<section class="invitation container"><div>${eyebrow('Your practice begins here')}<h2>Make a little room<br>for <em>yourself.</em></h2></div><div><p>Whether you’re stepping onto the mat for the first time or returning to your practice, there’s a place for you here.</p>${button('Explore our classes','classes')}</div></section>`;
const content = {};
content.index = `<section class="hero container"><div class="hero-copy">${eyebrow('A space to breathe. A place to grow.')}<h1>Come back<br>to <em>yourself.</em></h1><p>Find balance in movement. Find quiet in the everyday. Discover a yoga practice that meets you exactly where you are.</p><div class="hero-actions">${button('Find your practice','classes')}${button('Our story','about',true)}</div><div class="hero-note"><span class="sun-symbol" aria-hidden="true">✺</span><span>Every body. Every level.<br><strong>Everyone is welcome.</strong></span></div></div><div class="hero-visual">${image('hero','A woman finding a quiet moment in an outdoor yoga practice','hero-image')}<div class="image-caption"><span class="tiny-label">THE AARAV WAY</span><span>Rooted in tradition.<br>Open to you.</span></div><span class="orbit orbit-one" aria-hidden="true"></span><span class="orbit orbit-two" aria-hidden="true"></span></div></section>
<section class="values-strip"><div class="container"><span>Mindful movement</span><span class="spark" aria-hidden="true">✦</span><span>Intentional breath</span><span class="spark" aria-hidden="true">✦</span><span>A welcoming community</span><span class="spark" aria-hidden="true">✦</span><span>Space to grow</span></div></section>
<section class="section container"><div class="section-title"><div>${eyebrow('On the mat')}<h2>A practice for<br><em>every season of you.</em></h2></div><div><p>Some days call for movement. Others, for stillness.<br>Find the practice that feels right for you.</p><a class="text-link" href="classes.html">Discover all classes</a></div></div><div class="card-grid three">${classData.slice(0,3).map(classCard).join('')}</div></section>
<section class="story-section"><div class="container story-grid">${image('group','People practising yoga together in a bright studio','story-image')}<div>${eyebrow('Welcome to Aarav Yoga')}<h2>More than a practice.<br><em>A way of being.</em></h2><p>We believe yoga belongs to everyone. At Aarav Yoga, we make space for curious beginners, familiar faces, and all the paths in between.</p><p>Our approach is simple: thoughtful movement, a connection to the breath, and a little more kindness toward yourself.</p>${button('Get to know us','about')}</div></div></section>${invitation}`;
content.about = `${heading('Our story','Rooted in yoga.<br><em>Built around you.</em>','Aarav Yoga is a place to explore movement, reconnect with your breath, and make your practice your own.')}<section class="container story-grid about-story">${image('group','A shared yoga practice in a light-filled studio','story-image')}<div><h2>A little space.<br>A deeper connection.</h2><p>Yoga can begin with a single breath. Our vision is to create a welcoming space where you can start simply, learn at your own pace, and keep discovering.</p><p>We bring a considered approach to each practice, with options that respect different bodies, experiences, and rhythms. There is no perfect pose to achieve. There is only your practice, today.</p><p>As our community grows, this space will share the people, stories, and traditions behind Aarav Yoga.</p></div></section><section class="section container"><div class="section-title"><div>${eyebrow('What guides us')}<h2>Simple values.<br><em>Meaningful practice.</em></h2></div></div><div class="card-grid three">${[['01','A welcoming space','You don’t need flexibility or experience to begin. Curiosity is enough.'],['02','Mindful guidance','Explore each movement with care, awareness, and respect for your body.'],['03','Room to grow','A practice can change with you. Take what serves you and make it your own.']].map(([n,t,p])=>`<article class="value-card"><span class="card-number">${n}</span><h3>${t}</h3><p>${p}</p></article>`).join('')}</div></section>${invitation}`;
content.classes = `${heading('Find your practice','Movement. Stillness.<br><em>Your own rhythm.</em>','Explore our starting class collection. The weekly timetable, teachers, and prices will be shared soon.')}<section class="container classes-section"><div class="filter-row" role="group" aria-label="Filter classes"><button class="filter active" aria-pressed="true" data-filter="all">All classes</button><button class="filter" aria-pressed="false" data-filter="beginner">Beginner friendly</button><button class="filter" aria-pressed="false" data-filter="flow">Flow & movement</button><button class="filter" aria-pressed="false" data-filter="mindful">Mindful & gentle</button></div><p class="filter-summary" aria-live="polite">Showing 4 classes</p><div class="card-grid two">${classData.map(classCard).join('')}</div><div class="notice"><span class="sun-symbol" aria-hidden="true">✺</span><div><h3>Your first class</h3><p>Wear comfortable clothes, bring water, and arrive with an open mind. Mat availability and studio directions will be confirmed with the timetable.</p></div></div></section><section class="section container faq"><div>${eyebrow('A few things to know')}<h2>Start with<br><em>a little curiosity.</em></h2></div><div><details><summary>Do I need to be flexible?</summary><p>No. Choose a comfortable range of movement, and use variations that work for you. Yoga is a practice you can explore at your own pace.</p></details><details><summary>Which class should I start with?</summary><p>Our Hatha and Restorative descriptions offer a gentle starting point. Once our teachers and timetable are available, we can help you choose a class.</p></details><details><summary>When will the schedule be available?</summary><p>The class timetable and booking details will be added here soon.</p></details></div></section>`;
content.events = `${heading('Gather & connect','Shared moments.<br><em>Lasting connections.</em>','From mindful mornings to deeper explorations, discover what’s taking shape at Aarav Yoga.')}<section class="container event-list">${[['01','Community practice','A morning on the mat','A welcoming shared practice with gentle movement and a moment of stillness.'],['02','Workshop','The art of slowing down','An introduction to supported postures, restful pauses, and finding ease in your practice.'],['03','Seasonal gathering','Movement in nature','Space to breathe, move, and connect outdoors. Location and event details will follow.']].map(([n,kind,title,p])=>`<article class="event-card"><div class="event-marker"><span>${n}</span><small>COMING SOON</small></div><div><p class="eyebrow">${kind}</p><h2>${title}</h2><p>${p}</p><span class="status">Dates to be announced</span></div><a class="text-link" href="contacts.html">Event enquiries</a></article>`).join('')}</section><div class="container notice"><span class="sun-symbol" aria-hidden="true">✺</span><p>Our first events are being planned. Confirmed dates, venues, and registration details will appear here.</p></div>`;
content.instructors = `${heading('The people behind the practice','Thoughtful guidance.<br><em>Human connection.</em>','Meet the people who will help you find your rhythm on the mat. Our instructor introductions are coming soon.')}<section class="container instructor-intro"><div>${eyebrow('Our approach to teaching')}<h2>Space to learn.<br>Support to explore.</h2><p>A welcoming teacher can make all the difference. We value clear guidance, thoughtful options, and an approach that respects each person’s practice.</p><p>This page will introduce our instructors, their teaching styles, experience, and the classes they lead.</p><a class="text-link" href="classes.html">Explore the class collection</a></div>${image('group','A group practising yoga in a bright shared space','story-image')}</section><section class="section container"><div class="card-grid three">${[['Foundations','Clear, considered instruction','Explore the basics and build familiarity with postures and breath.'],['Connection','Practice at your own pace','Find options that feel right for you, with space to ask questions.'],['Presence','A thoughtful experience','Notice how you feel, stay curious, and return to your practice with care.']].map(([label,title,p])=>`<article class="value-card"><p class="eyebrow">${label}</p><h3>${title}</h3><p>${p}</p></article>`).join('')}</div></section>`;
content.gallery = `${heading('A glimpse of the practice','Little moments.<br><em>A quieter perspective.</em>','A visual starting point for Aarav Yoga. Studio, class, and community photographs will be added as our story unfolds.')}<section class="container gallery-grid">${[['hero','A moment outdoors','Quiet & connection'],['group','Together on the mat','Movement & community'],['detail','Space for your practice','Simple rituals']].map(([asset,title,label],i)=>`<button class="gallery-item gallery-item-${i}" data-image="assets/${asset}.jpg" data-caption="${title}" aria-label="View photo: ${title}">${image(asset,title)}<span class="gallery-caption"><small>${label}</small><strong>${title}</strong><span class="expand-icon" aria-hidden="true">+</span></span></button>`).join('')}</section><p class="container gallery-note">Illustrative photographs for our first collection. Our own Aarav Yoga gallery is coming soon.</p><dialog class="lightbox" aria-labelledby="lightbox-caption"><button class="dialog-close" aria-label="Close photo">×</button><img id="lightbox-image" alt=""><p id="lightbox-caption"></p></dialog>`;
const articles = [
  ['Beginning your practice','Your first time on the mat','A few gentle reminders for starting yoga with curiosity and confidence.','Starting something new can feel unfamiliar. You do not need to arrive with experience, flexibility, or a perfect idea of what yoga should look like.','Choose a comfortable pace, make space for questions, and let your teacher know that you are new. Take breaks when you need them. A smaller movement can be just as useful as a bigger one.','Your practice is an opportunity to notice, rather than perform. Begin with what feels manageable, and give yourself time to learn.'],
  ['Everyday rituals','Making room for a pause','Small ways to bring a moment of presence into an ordinary day.','A pause does not have to be long. It can be the moment before you start your morning, the space between tasks, or a few quiet minutes at the end of the day.','Find a comfortable seat, let your shoulders soften, and notice the natural rhythm of your breath without trying to change it. You can keep your eyes open and rest your gaze on something still.','There is no need to force a result. A brief, comfortable pause is enough. Return to your day when you are ready.'],
  ['On the mat','Movement or stillness?','Learning to choose a practice that fits the way you feel today.','Some days you may want a flowing practice. On others, a slower pace or a supported resting posture can feel more fitting. Your practice does not have to look the same each time.','Before you begin, take a moment to notice your energy, your available time, and what you feel ready to explore. Consider a familiar sequence or simply a few easy movements.','You can change your mind as you go. Choosing an easier variation, taking a break, or ending earlier can be part of a thoughtful practice.']
];
content.blogs = `${heading('The Aarav journal','Thoughts for the mat.<br><em>And the everyday.</em>','Simple reflections on practice, presence, and finding a little more space in your day.')}<section class="container journal-grid">${articles.map(([category,title,summary],i)=>`<article class="journal-card">${i===0?image('detail','Yoga props ready for practice'): `<div class="journal-art art-${i}" aria-hidden="true"><span>${i===1?'Pause.':'Be here.'}</span><div class="art-ring"></div></div>`}<div class="journal-copy"><p class="eyebrow">${category}</p><h2>${title}</h2><p>${summary}</p><button class="text-link" data-article="${i}">Read the story</button></div></article>`).join('')}</section><dialog class="article-dialog" aria-labelledby="article-title"><button class="dialog-close" aria-label="Close article">×</button><p id="article-category" class="eyebrow"></p><h2 id="article-title"></h2><div id="article-body"></div></dialog><script type="application/json" id="article-data">${JSON.stringify(articles).replace(/</g,'\\u003c')}</script>`;
content.contacts = `${heading('Let’s connect','Your next chapter<br><em>starts with a hello.</em>','Questions about classes, events, or beginning your practice? Our contact details will be available here soon.')}<section class="container contact-grid"><div class="contact-panel"><p class="eyebrow">Visit Aarav Yoga</p><h2>A space for<br>your practice.</h2><dl><div><dt>Our studio</dt><dd>Studio address coming soon</dd></div><div><dt>Email & phone</dt><dd>Contact details coming soon</dd></div><div><dt>Opening hours</dt><dd>To be shared with our class timetable</dd></div></dl><p class="contact-note">We’re preparing the details. Check back for directions and ways to get in touch.</p></div><div class="contact-options"><div id="enquiry-context" hidden></div>${eyebrow('Find what you’re looking for')}<h2>Let us point you<br><em>in the right direction.</em></h2><a class="contact-link" href="classes.html"><span>Class enquiries</span><small>Explore styles and find your starting point</small></a><a class="contact-link" href="events.html"><span>Events & workshops</span><small>See what’s being planned</small></a><a class="contact-link" href="about.html"><span>About Aarav Yoga</span><small>Get to know our approach</small></a></div></section>`;
const icon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="16" fill="#174D2B"/><path d="M32 13c-12 13-12 24 0 35 12-11 12-22 0-35Z" fill="none" stroke="#FAF8F2" stroke-width="3"/><path d="M14 28c0 14 6 21 18 21M50 28c0 14-6 21-18 21" fill="none" stroke="#F2A51A" stroke-width="3" stroke-linecap="round"/></svg>`;
writeFileSync(`${out}/assets/favicon.svg`,icon);
for(const [slug,title] of pages){
  const nav=pages.map(([s,t])=>`<a href="${link(s)}" ${s===slug?'aria-current="page"':''}>${t}</a>`).join('');
  writeFileSync(`${out}/${slug}.html`, `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#174D2B"><title>${slug==='index'?'Aarav Yoga · Come back to yourself':`${title} · Aarav Yoga`}</title><meta name="description" content="${title} at Aarav Yoga. Explore mindful movement, yoga classes, and a welcoming approach to your practice."><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,${encodeURIComponent(icon)}"><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script></head><body data-page="${slug}"><a href="#main" class="skip-link">Skip to content</a><header class="site-header"><div class="container header-inner"><a class="brand" href="index.html" aria-label="Aarav Yoga home"><span class="brand-mark" aria-hidden="true">a</span><span>aarav<span class="brand-sub">YOGA</span></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="primary-nav" aria-label="Open navigation"><span></span><span></span></button><nav id="primary-nav" aria-label="Main navigation">${nav}</nav></div></header><main id="main">${content[slug]}</main><footer class="site-footer"><div class="container footer-main"><div><a class="brand footer-brand" href="index.html"><span class="brand-mark" aria-hidden="true">a</span><span>aarav<span class="brand-sub">YOGA</span></span></a><p>A little movement.<br>A little stillness.<br>A little more you.</p></div><div class="footer-links"><p class="footer-label">EXPLORE</p>${pages.slice(1,5).map(([s,t])=>`<a href="${link(s)}">${t}</a>`).join('')}</div><div class="footer-links"><p class="footer-label">CONNECT</p>${pages.slice(5).map(([s,t])=>`<a href="${link(s)}">${t}</a>`).join('')}</div><div class="footer-message"><span class="sun-symbol" aria-hidden="true">✺</span><p>Make space<br>for what matters.</p></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} Aarav Yoga. All rights reserved.</span><span>Move mindfully. Live gently.</span></div></footer></body></html>`);
}
console.log(`Created ${pages.length} Aarav Yoga pages.`);
