const events = [
  { title: 'A morning on the mat', category: 'Community', image: 'group.jpg', alt: 'A shared yoga practice', description: 'A welcoming shared practice with gentle movement and a moment of stillness.' },
  { title: 'The art of slowing down', category: 'Workshop', image: 'editorial-studio.jpg', alt: 'Yoga mats arranged in a sunlit studio', description: 'An introduction to supported postures, restful pauses, and finding ease in your practice.' },
  { title: 'Movement in nature', category: 'Outdoor yoga', image: 'hero.webp', alt: 'Meditation on a tropical beach', description: 'Space to breathe, move, and connect outdoors. Location and event details will follow.' },
  { title: 'A moment to breathe', category: 'Mindfulness', image: 'editorial-pair.jpg', alt: 'Two people sharing a seated yoga practice', description: 'Explore gentle breathing and guided moments of stillness in a welcoming shared practice.' }
];

export function renderEvents() {
  return `<section class="event-tiles" aria-label="Upcoming yoga events">${events.map((event, i) => `<article class="event-tile"><img src="assets/${event.image}" alt="${event.alt}" width="800" height="800" loading="${i < 2 ? 'eager' : 'lazy'}" decoding="async"><div class="event-tile-copy"><p class="event-date">Coming soon</p><h2>${event.title}</h2><span class="event-category">${event.category}</span><button type="button" class="event-read-more" data-event="${i}" aria-label="Read more about ${event.title}" aria-haspopup="dialog">Read more <span aria-hidden="true">→</span></button></div></article>`).join('')}</section><dialog class="event-dialog" aria-labelledby="event-title"><button class="dialog-close" type="button" aria-label="Close event details">×</button><p id="event-category" class="eyebrow"></p><h2 id="event-title"></h2><p id="event-description"></p><p>Dates, venues, and registration details will be announced soon.</p><a class="button" href="https://wa.me/919958834005?text=${encodeURIComponent('Hello Aarav Yoga! I would like to know more about your upcoming events.')}" target="_blank" rel="noopener noreferrer">Enquire on WhatsApp</a></dialog><script type="application/json" id="event-data">${JSON.stringify(events).replace(/</g, '\\u003c')}</script>`;
}
