const reviews = [
  ['Amit', '', 'Aarav Yoga is the best yoga center which teaches different types of yoga like power yoga, hatha yoga, Vinyasa, Ashtanga, meditation, and breathing techniques. As its motive is clear to spread spirituality of yoga amongst the youth.'],
  ['Priyanka', 'Choreographer', 'There are so many Yoga centres near my locality but Aarav Yoga is one of the most finest and deserving Yoga centre in mine locality. Their faculties are very helpful towards every student.'],
  ['Rahul Jha', 'Fashion Designer', 'Aarav Yoga’s teachers are very decent and experienced. They can teach you yoga in a very helpful manner, at every single point or bend. Also the surrounding is very awesome where classes are conducted.'],
  ['Vipin Kumar', 'Photographer', 'Aarav Yoga’s is very affordable yoga centre I’ve ever seen. The prices are too efficient with the best trainers for every sessions. Just started sending my parents to this centre in evening classes and they are happy too']
];

export function renderTestimonials() {
  return `<section id="testimonials" class="testimonials-editorial section-space" aria-labelledby="testimonials-title"><div class="testimonials-heading"><h2 id="testimonials-title">What Our Students Say</h2></div><div class="reviews-carousel" role="region" aria-roledescription="carousel" aria-label="Student testimonials"><div class="reviews-track" tabindex="0" aria-label="Swipe or use arrow keys to browse reviews">${reviews.map(([name, role, text], i) => `<article class="review-card" role="group" aria-roledescription="slide" aria-label="${i + 1} of ${reviews.length}: ${name}"><span class="review-quote" aria-hidden="true">“</span><blockquote>${text}</blockquote><div class="review-author"><span class="review-avatar" aria-hidden="true">${name.split(' ').map(part => part[0]).join('')}</span><div><strong>${name}</strong>${role ? `<span>${role}</span>` : ''}</div></div></article>`).join('')}</div><div class="reviews-controls" hidden><button type="button" class="reviews-prev" aria-label="Previous testimonial">←</button><p class="reviews-status" role="status" aria-live="polite">1 of ${reviews.length}</p><button type="button" class="reviews-next" aria-label="Next testimonial">→</button></div></div></section>`;
}
